---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: files-rclone
    includeSelectors: true
resources:
  - ./deployment.yaml
  - ./secret.sops.yaml
  - ./service.yaml
  - ./httproute.yaml
namespace: files
