# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: rclone-webdav
stringData:
  RCLONE_USER: ENC[AES256_GCM,data:tFhqwCEa8f+QmA==,iv:LdNw6eaySYqeFfftksCwE+/HZTXi4dqSj7rU/CDvcQU=,tag:L2RmZdbZ1HQCznON+MDHvA==,type:str]
  RCLONE_PASS: ENC[AES256_GCM,data:iN8iEHReQoEOSZjX,iv:Kww+icAYrUKTp99FXj3NVvYWqwgcLbR2CQhBLWmcfLA=,tag:a7Y6MXWv1oGGuNYwprPxbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVjNqZ2RzaGpKOGxKL2FT
        Ykp0V3BWUDlZRXhzK2hpYUFTTXg5UEVJeEdrCjBUb3dSSzlWUEdtN3Z5MjA0VlNK
        TFN4WGxsMjkrY3p1Ymt4WGk1SVpXVm8KLS0tIE1VNFY3M0xYWG8rdHZFWHVaUk5M
        bFh5ZXphL0E5M2RGL0h4c0hZMjdWdmcKr29BZXVBO2C3YoNIYRTG/YSnOzZjl0Mb
        f9jcZsSv2/HpAsQBP+330RuKtTWAIiAB86WNuH1J141pxfOMbHEqnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T04:02:12Z"
  mac: ENC[AES256_GCM,data:esEasL62JvPFPJ+IM1VjqfvYk725OLp8dB2oP/X3Cd7gD5ITbxZWnmbWF6K0k2q7s9KKsBGDQChjXDnUR/CCqq4uYYIxX0CD5I3Oj6j3BGrODI4JasDIXbzgz/oSL+XNeEulePqLunRPofrX1TrHb7DnDuEWKSwTBL/HdRgCXxA=,iv:e+gtUEw219S0vaibkNbt8C4anYiZ2ETRMzKBCPpiUW4=,tag:5TIRfH2l+J81t/ix9UwwdA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
