---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustfs
resources:
  - ./repos/
  - ./rustfs-clustersettings.secret.sops.yaml
  - ./rustfs.yaml
components:
  - ../../components/clustersettings/
