# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-clustersettings
  namespace: flux-system
stringData:
  RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:XYOpjuzd,iv:EhQiDadLysQvf0AloXyPze+I7cU/L4akzW1KE7hntUA=,tag:49s8/LdFW3CIsqS30rvBgA==,type:str]
  RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:qJgGIy/K,iv:GmrngdVx6MRkXuEhPohgKHKd/8oj0C1u1cyXUWHxhrY=,tag:21k0pjihBQJrVFw7kyTEpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTmU2ZnRDcE1lalNnUldX
        UWlRZys0TytNaEZSNTZ1bS9uZUVNUjFxN2hNCmE0RnlsZjJUUGVGdVdGNlhieisw
        NUI4RTUvWTZxT2psUEFkOHU3cjExK00KLS0tIFBKT1FNWWZ5bUFrWVBidDJXMk9t
        SVhoTXRLUE1INDBuUHFpUUxuQlMrSUUK5y7p7CPWvZIGXjqQ+A14wG+Y5C61PCjZ
        X2cXPv9xmXNSRcOdXPAOdQehV26c8pZA+V1Li94L+vS1xKpXZk3GMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T17:23:37Z"
  mac: ENC[AES256_GCM,data:x6Krew8FMW2mlYkQhBO5How65QJXQNRsII/g/VeMkOQ3JHMv/i1n21XYYQMjl4xnMoisVjHsq6GYadSsOxm21/BEwsE+NbFfbNJw83moQqBRt9EC4QSL+KN5Yr+agqaqNyPVWHHikKjWx/mgy8jRqchCrR9HIs+nWm+xqRBNGWA=,iv:STxstrIJEtINpJID9s9EZcR0UtQehtYZcGm0dlzjxHc=,tag:/Kg/mfZTTCth+cxny9Quug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
