---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mltb
    includeSelectors: true
resources:
  - ./base.httproute.yaml
  - ./deployment.yaml
  - ./env.configmap.yaml
  - ./env.secret.sops.yaml
  - ./rlcone.httproute.yaml
  - ./sa-accounts.secret.sops.yaml
  - ./sa-token.secret.sops.yaml
  - ./service.yaml
images:
  - name: ghcr.io/kevinnitrog/homelab/mltb
    digest: sha256:33294246cbb2b581812378199f3d13162fe3366c2430809a46608474c76f01c8
