---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mltb
    includeSelectors: true
resources:
  - ./base.httproute.yaml
  - ./deployment.yaml
  - ./env.configmap.yaml
  - ./env.secret.sops.yaml
  - ./rlcone.httproute.yaml
  - ./sa-accounts.secret.sops.yaml
  - ./sa-token.secret.sops.yaml
  - ./service.yaml
images:
  - name: ghcr.io/kevinnitrog/homelab/mltb
    digest: sha256:19fe5e1d8b9f5d445666f969a1892498ee35da285e2734a2ef5119d7091ae0bf
