---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mltb
    includeSelectors: true
resources:
  - ./base.httproute.yaml
  - ./deployment.yaml
  - ./env.configmap.yaml
  - ./env.secret.sops.yaml
  - ./rlcone.httproute.yaml
  - ./sa-accounts.secret.sops.yaml
  - ./sa-token.secret.sops.yaml
  - ./service.yaml
images:
  - name: ghcr.io/kevinnitrog/homelab/mltb
    digest: sha256:4c73192520e8c42a6b00bce7b99e6cd621a5937d880ccc4844ae8b91680c1f14
