---
# K3s cluster variables (only used by site.yml)
k3s_version: "v1.36.4+k3s1"
flux_version: "2.9.4"

github_owner: KevinNitroG
github_repo: homelab
github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
