default:
  @just --list

gen-drive-token *args:
  uv run \
    --python 3.13 \
    --with google-api-python-client \
    --with google-auth-httplib2 \
    --with google-auth-oauthlib \
    --no-project \
    ./anasty17-mltb/generate_drive_token.py {{args}}

gen-sa *args:
  uv run \
    --python 3.13 \
    --with google-api-python-client \
    --with google-auth-httplib2 \
    --with google-auth-oauthlib \
    --no-project \
    ./anasty17-mltb/gen_sa_accounts.py {{args}}

[unix]
[doc('Extract email from service accounts folder')]
extract-emails folder='accounts' out='emails.txt':
  grep -oPh '"client_email": "\K[^"]+' {{folder}}/*.json > {{out}}

[windows]
extract-emails folder='accounts' out='emails.txt':
  $emails = Get-ChildItem .{{folder}}\**.json |Get-Content -Raw |ConvertFrom-Json |Select -ExpandProperty client_email >>{{out}}

create-k8s-sa-accounts-secret:
  kubectl create secret generic sa \
  --from-file=./accounts/ \
  --dry-run=client -o yaml > ./manifests/mltb/secret-sa.sops.yaml

create-k8s-sa-token-secret:
  kubectl create secret generic sa-token \
  --from-file=./token_sa.pickle \
  --dry-run=client -o yaml > ./manifests/mltb/secret-sa-token.sops.yaml

merge-sa:
  jq -s '.' ./accounts/* > combined-sa.json
