---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-filebrowser
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      name: filebrowser-filebrowser
    spec:
      initContainers:
        - name: import-users
          image: filebrowser/filebrowser:v2.63.21
          command:
            - filebrowser
            - --database=/database/filebrowser.db
            - users
            - import
            - /config/user.json
          volumeMounts:
            - name: filebrowser-user
              mountPath: /config/user.json
              subPath: user.json
            - name: filebrowser-database
              mountPath: /database/
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.63.21
          args:
            - --config=/config/config.yaml
          ports:
            - containerPort: 80
          volumeMounts:
            - name: &config filebrowser-config
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: &database filebrowser-database
              mountPath: /database/
            - name: &aria2 aria2-downloads
              mountPath: /srv/aria2/
            - name: &metube metube-downloads
              mountPath: /srv/metube/
      volumes:
        - name: *config
          configMap:
            name: *config
        - name: *database
          persistentVolumeClaim:
            claimName: *database
        - name: *aria2
          persistentVolumeClaim:
            claimName: *aria2
        - name: *metube
          persistentVolumeClaim:
            claimName: *metube
        - name: filebrowser-user
          secret:
            secretName: filebrowser-user
  selector: {}
