---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: files-filebrowser
    includeSelectors: true
resources:
  - ./config.configmap.yaml
  - ./database.pvc.yaml
  - ./deployment.yaml
  - ./httproute.yaml
  - ./service.yaml
  - ./user.secret.sops.yaml
namespace: files
