# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-user
stringData:
  #ENC[AES256_GCM,data:3Eghyrnuytdy0vDuwNyZ,iv:am7jdVXtNiI6PwwEmgDJ5dI0gmA5Hvtoa1Jlp3o1k5M=,tag:Qd+w86nCmBDsSbEB9BssFA==,type:comment]
  user.json: ENC[AES256_GCM,data:u/TrQonLazB+Qok5JBgGiDVoq/LH1Xp8XYwILhfg1e9+gVUDjU0ZInyJgeLtm7jd7BoVKSq3PDoZjKh77oOCI9U/yG14eJl+jxwRxly2UfVQ3H9h9UC7iZAFgzco9ryY0+zzy6SnGlmKf/vYao9phsM4ZA41j3TmJB4+TVjSPzHWAP2c5BxtTQ==,iv:a5nmIJ36QTSR3qWfQLAa8/8HthZWql6Lch6RDIXWsmo=,tag:9Y9fAXAciFKc52XRDjTRJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITXg4OE5sanE0VFJ3clI2
        eVdvYTNGM25EczZ0OTJOUFBWQ1lORytpRG5rCmFtRUN5NkkxaFFUZmEwSkI4b3Fj
        QzA0OWY4QWpLeDJOUDltZ1JYSkN4YXcKLS0tIEhyTjhnNm01a0NTSzd2S1FOR2dl
        bjdzNFNVWGFucU5rZ09qbFBxTmdmT1UKc2gKNT7pf/eLuK/KKH+9qjSjUpfXUoMQ
        fXEYNutmd5uLnFLQs9dGLxKtjvJqg879ESFMp5M5Z1MZFOSHWwHNgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T05:52:15Z"
  mac: ENC[AES256_GCM,data:N4DoOh2cCyNstkrjP98J7/axlkIKMUZYT3vUpigrJfTLmhB+ENihVz+AGzv7GroESUilJIfLNYt+Nb0rMS2pZ+AIJfwqtZ35HpVttIK619MdyXObdAOsfcMgF4RfZ4FZEVnYMHFM0NSKQAp8QxsyAKIhdg2lLEfLtSPkTGl4Lko=,iv:Rtrw2SalccIQ2KVwvvk7hlHqUm3VofXPYOcQskqhd0o=,tag:ggL9LoP9L76DWUGP0l9pLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
