# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-user
stringData:
  #ENC[AES256_GCM,data:Jw2173NJsPCHs081ZlcZ,iv:slZigizXhPlvSAMvMQtD+KjbT8wPrHT99mDB30pXfnU=,tag:hcjqdsbjJ7doEj8SkO9SEA==,type:comment]
  user.json: ENC[AES256_GCM,data:pUOGSQKnA+WGbuh59zKwI2cgPukOvEM3XhRNggkPpSbz3RyHd6X6aBmoQaJMUDXgSM16eH10BnOuknHOA6R7fjj06Z5lGjtq5XuV39/b8X6LGx5yHsdQna41wknZZx3QZU1BrshDEB20T166jrX6OXsIgX9Xfh+/+bAvXN9B8uDTzAOh,iv:IjAe4hI0Rpx2IVsxrsoJ1hhyjEENLnrosiGGLEMZ5a8=,tag:1eRLtYeoS81ObTVOUvwm1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZFhDN3NMQzNTTWp3M0ZE
        NDFVTnNQczFtTWJGdjlab1RJdGtTK3hkSzBBCkVvOTV4Q2tBUUJxVzYwK1F3bmpD
        ZktaMlQxaGkxMUFBWFMvV0RFSDVsRmcKLS0tIDE4Y0xaMHd5c1lMcXhkOGpRdTNZ
        SXY5RHJNV2tJK2crVUNUdGRYNDhSZ0kKKqbqrjILgNGhlDBDa6zKHijCZWzxTfcp
        9zh6X6PQDzlc/USw6yavJ8himYGljiwISLURvdnxAUt5DdWlOlMEPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T05:08:48Z"
  mac: ENC[AES256_GCM,data:LLS+G95KIM3vM0hWVTPooJIQWPV5Ur799yPaRtVIUKtmWkaBxVutznyo5KZDATYJmp4Vwc6rq1qh1LIRsmaSwC2ED1ddpx3BNhCduV4uPQ4orgiB+lC9RG83UyUJzyv9fvZEVPEaDjnyTrJ5FCu4ccgf89oYLWzhvhP1XI325W8=,iv:K8KffecL47lWtDRgvwO75ZjIWq5fF3qc1BMpKbDbAeo=,tag:IEP5eziBUTdDRGtFhA9a8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
