# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-user
data:
  #ENC[AES256_GCM,data:Vf508LbzMHUot11/MCWC,iv:Ic1XR3hpgQjoB4Qkc+IR5eDPDialAu0PJsQGY6jZO6M=,tag:/V02GIayKSlt8qp+b8fQzw==,type:comment]
  user.json: ENC[AES256_GCM,data:mHgu4Jg42JDa2TeAWn+STfcv/JFcd5y1EL2D409eK2/sHYqE7MeeJbrewFUB+NF85PNNRLOLXVZpqu+d/oiQY6PmGAx36uFP83Ri2QGHldSzTaLkYRCIPbau+biMMNATROpMBPFAcM2ywig4JL1+MLQ+PCEE/OMLBnaiKkc1tnKir6NZ,iv:wW7WFp2skKSfK7axnheQXtAo+fe/M5UVMXGBvDYEHH4=,tag:rA47NadRDXLNtlZ2mGj8dg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NkNqMVVlczNxWCsvc3dX
        YWRPZjIyRTlEUHBPekdpRmhETU5mZyt3cld3Clc2aWVKVURBUmlUNEZST0RpRnJn
        M0V6eVJNeHdadk9mRjFXOUl3bFZFSHMKLS0tIDduS011YlBFRFBXWWhiL25UVVFT
        bmh1K1Z1MVphZlJBTnFlRzZDMUlNMG8KCFUC+lNdKASLmzZHom6JqiXNDNqLaqmS
        FrhnEa4PTEoPWtqhay6vJjv+Nv8bj/PpG4gWhB5dHX9KYGKS8yIlUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T04:53:42Z"
  mac: ENC[AES256_GCM,data:p1DIuOB0smZuJ7r0Fq7Yb3YSgqx5/igbQuww6LDG/7X1jAqK62A+FzYVJHp/IPKmCvCERXaCRdxhaVErWfdMMPO2OO2L/sTATN8f9Z/G3t5LcBBnX0dLaiyRkc5Yj+oisNN7Bbjd4DRRjqBT8Ykj/NoeOhJA+vBOwtFyzQqoWTo=,iv:mv9feREYtQsVTIR1Ljwlc1TyT546V1zI/2eVE5h8dck=,tag:DsrlNbIOLZkrlZ/5GkMjKA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
