# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-clustersettings
stringData:
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:15lPr8dj7OPR,iv:gDkzLw7JgEpfjRiHDBMhdwU+PcOnBlWRZmhblDtbTqQ=,tag:w48jKTSZvi9msCjpfTFFDQ==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:UEnGdSfUcAko,iv:dMiZTjnfcOTGytHpJsXF7lTTWQBP01ZMbE8on//YUp4=,tag:LTy3w2vcWj1Ah0qqGrqZPw==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:cvyT4zEzZFf+,iv:YJx3zQHl1b8RbBwqAfIj3xvlBrITFi2l2h9wFt9gdwQ=,tag:cQq2fDZNdTGUXOL7fRC4Fg==,type:str]
  AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:t4eh5HOhrqyk,iv:sh8taXGQtdyQvt46aT8HkHYaFSaoLcKkvw76UqfuKUU=,tag:KX7FUUHLCBltfVctrCQorA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT1JPS1MxY3RzU29XdFJQ
        K0Z5VXdKZFYvVDlMcG1ES1o3YVQveVhlTEdJCnN3d2hxRDR4OVFCVnJKaTI5cUFz
        VFFYK2ZXOG1sYU9FODB5RHRrTm1NZ3cKLS0tIDZCZGFxOFFDbWttWk9MVVVoSHNL
        YlFVKzlKSkhtTkFyY0tjMHJtelorcVUKMcXVYUfudplyM8ukeh1R2GFWiRqL421S
        83orlXZ5tptVtDm861qemOJp7yqm1h+cux1zrzbg5rRBxc9aGWcKCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T16:48:22Z"
  mac: ENC[AES256_GCM,data:s0hn9ZOOXrArEdqqNn8yMQoQogKCMLRxfFP5FZLiWHljW3UYb2o3FlPwKsOQBHbxQ5K4GgRPNx9eYgE+0cekPDPwWwNGrhNo8bfJqvVrnPN4Qnya572r6LNCB2fdALlFmFV8FS7uT6UqUy1+2HLOiUJN/5rLjTupETOqwDaMRew=,iv:r0vMDikUALj2sWfVnuwESdqTN3jWos9aL3Bp2n8c64g=,tag:ag43fiWFN7+PvcPePfMcJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
