---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization # don't use component, because I cannot patch configmap and secret separately
resources:
  - ../../../base/rustfs/rustfs/
patches:
  - target:
      kind: HelmRelease
      name: rustfs
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |- # language: yaml
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: rustfs-helm-values
secretGenerator:
  - name: rustfs-helm-values
    files:
      - values.yaml=./values.yaml.encrypted
configurations:
  - ./kustomizeconfig.yaml
