---
k3s_cluster:
  children:
    server:
      hosts:
        kevblink:
          ansible_host: 192.168.28.25
          ansible_user: kevinnitro
  vars:
    server_config_yaml: | # language: yaml
      write-kubeconfig-mode: "0644"
      tls-san:
        - kev
        - kevinnitro.id.vn
      disable:
        - traefik
        - servicelb
