---
# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json
server:
  proxied: true
branding:
  hide-footer: true
  logo-text: K
  app-name: Kevglance

pages:
  - name: Home
    desktop-navigation-width: slim
    head-widgets:
      - type: search
        autofocus: false
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Kite
                check-url: http://kite.kite:8080/healthz
                url: https://kite.kevinnitro.id.vn
                icon: sh:kite-kubernetes
              - title: Grafana
                check-url: http://grafana-service.monitoring:3000/api/health
                url: https://grafana.kevinnitro.id.vn
                icon: si:grafana
              - title: Prometheus
                check-url: http://monitoring-kube-prometheus-prometheus.monitoring:9090/-/ready
                url: https://prometheus.kevinnitro.id.vn
                icon: si:prometheus
              - title: Alertmanager
                check-url: http://monitoring-kube-prometheus-alertmanager.monitoring:9093/-/ready
                url: https://alertmanager.kevinnitro.id.vn
                icon: mdi:torch
              - title: Loki
                check-url: http://loki-loki.monitoring:3100/ready
                url: https://loki.kevinnitro.id.vn
                icon: sh:loki
              - title: Tempo
                check-url: http://tempo-tempo.monitoring:3200/ready
                url: https://tempo.kevinnitro.id.vn
                icon: sh:tempo
              - title: Alloy
                check-url: http://alloy-alloy.monitoring:12345/-/healthy
                url: https://alloy.kevinnitro.id.vn
                icon: sh:grafana-alloy
              - title: Authentik
                check-url: http://authentik-server.authentik:80/-/health/live/
                url: https://authentik.kevinnitro.id.vn
                icon: si:authentik
              - title: DbGate
                check-url: http://dbgate.dbgate:8978/status
                url: https://dbgate.kevinnitro.id.vn
                icon: si:dbeaver
              - title: Ariang
                check-url: https://ariang.mayswind.net/latest/#!/settings/ariang
                url: https://ariang.mayswind.net/latest/#!/settings/rpc/set/https/aria2.kevinnitro.id.vn/443/jsonrpc/$${ARIA2_RPC_SECRET}
                icon: sh:aria2
              - title: Metube
                check-url: http://metube.files:8081
                url: https://metube.kevinnitro.id.vn
                icon: sh:metube
              - title: Filebrowser
                check-url: http://filebrowser.files:80/health
                url: https://filebrowser.kevinnitro.id.vn
                icon: sh:file-browser
              - title: MLTB
                check-url: http://mltb-mltb.mltb
                url: http://mltb.kevinnitro.id.vn
                icon: si:telegram
          - type: bookmarks
            groups:
              - title: Mine
                links:
                  - title: Kevindex
                    url: https://kevindex.kevinnitro.id.vn/
                    icon: si:cloudflareworkers
      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: kevblink
          # - type: extension
          #   url: http://glance-k8s/extension/nodes
          #   allow-potentially-dangerous-html: true
          #   cache: 10s

  - name: News
    desktop-navigation-width: slim
    columns:
      - size: full
        widgets:
          - type: rss
            title: UIT
            style: detailed-list
            cache: 1h
            feeds:
              - url: https://www.uit.edu.vn/taxonomy/term/83/feed
                title: General Notifications
              - url: https://www.uit.edu.vn/taxonomy/term/87/feed
                title: UIT News
              - url: https://www.uit.edu.vn/taxonomy/term/202/feed
                title: Study
              - url: https://www.uit.edu.vn/taxonomy/term/201/feed
                title: Student Activities
          - type: rss
            title: UIT Forum
            style: detailed-list
            cache: 1h
            feeds:
              - url: https://forum.uit.edu.vn/posts.rss
                title: Posts
              - url: https://forum.uit.edu.vn/latest.rss
                title: Latest Topics
              - url: https://forum.uit.edu.vn/c/ho-tro-doi-song/viec-lam-thuc-tap/32.rss
                title: Internship
              - url: https://forum.uit.edu.vn/c/ho-tro-doi-song/hoi-thao-tham-quan-doanh-nghiep-cac-cuoc-thi/33.rss
                title: Companies
              - url: https://forum.uit.edu.vn/c/goc-hoc-tap/cong-nghe-phan-mem/20.rss
                title: Software Falcuty
              - url: https://forum.uit.edu.vn/c/cong-dong-uit/10.rss
                title: Network Falcuty

theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
  presets:
    catppuccin-frappe:
      background-color: 229 19 23
      contrast-multiplier: 1.2
      primary-color: 222 74 74
      positive-color: 96 44 68
      negative-color: 359 68 71
    catppuccin-macchiato:
      background-color: 232 23 18
      contrast-multiplier: 1.2
      primary-color: 220 83 75
      positive-color: 105 48 72
      negative-color: 351 74 73
    catppuccin-latte:
      light: true
      background-color: 220 23 95
      contrast-multiplier: 1.0
      primary-color: 220 91 54
      positive-color: 109 58 40
      negative-color: 347 87 44
