# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json#/properties/pages
- name: News
  desktop-navigation-width: slim
  columns:
    - size: full
      widgets:
        # Forum + YouTube (side by side)
        - type: split-column
          widgets:
            # Forum
            - type: rss
              title: Forum
              style: detailed-list
              cache: 1h
              feeds:
                - title: Voz Chuyện trò linh tinh
                  url: https://voz.vn/f/chuyen-tro-linh-tinh.17/index.rss
                - title: Voz Tuyển dụng tìm việc
                  url: https://voz.vn/f/tuyen-dung-tim-viec.95/index.rss
                - title: Voz Lập trình CNTT
                  url: https://voz.vn/f/lap-trinh-cntt.91/index.rss
                - title: r/vozforums
                  url: https://www.reddit.com/r/vozforums/.rss
                - title: r/neovim
                  url: https://www.reddit.com/r/neovim/.rss

            # YouTube: Tech
            - type: videos
              title: YouTube - Tech
              style: horizontal-cards
              cache: 1h
              limit: 20
              channels:
                - UC3ECq823SyuR1Is4zhxfuOA # TheLinuxNinja
                - UCYeiozh-4QwuC1sjgCmB92w # devopstoolbox
                - UCMN0a7GHQnC6H74SmCGSmdw # yousuckatprogramming
                - UCqAL_b-jUOTPjrTSNl2SNaQ # SoftwareDeveloperDiaries

            # YouTube: Blog
            - type: videos
              title: YouTube - Blog
              style: horizontal-cards
              cache: 1h
              limit: 20
              channels:
                - UChfAI8bOPOJIQOTE-qHRwew # tumivn
                - UC7aT5OieA6-AGD48qZCDnUA # vinamuse203
