# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: sops
  namespace: egolia
data:
  age.agekey: ENC[AES256_GCM,data:zca9osyfLOS5V7kJQ+LCOXpAoZ7z2oL/4tlNA6uFmqVkJGNrmfBcfEGQXg6jTiIZKQIKvFn8GRgsxuWYnGGoQx/PJDQKeW2WuOGPPzC1+59d2Mn7QSgOJgMS9gvLzhiLLFAZl+t5uQzU6wQyL+mXnmhdxT66V25x8tr80PtQGo2cSEfkvJwGpHim0rA0WnOOEff9VRI86P8rQMM8DMoUgslSPsvBICft9PZHtghNymjFhioX60lARlHvozio,iv:hP1If4aqS7KdT6AhvALicRzcrCOtHhXn8smzZ/WwDlI=,tag:7sVEI2MV7NgYBCBtgZg08Q==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja3BDNmNSQWh5V0Z2Zng1
        L0JobHE2SE00ZUl0WDVVamVhbEtiZGZsenpVCnlRS0Vkb2RwSVBOQmx3aTJBVzQy
        U0NqMitpOWFqSmFXY2E4cXZFUEJ3ckEKLS0tIGdwKzdUNTZibW43eFlFMnRwZEo4
        bDV4V1pxTTdrNzNHUnZkbExldm41blkKDnfHTzpAh9Zr8fdeRpFfgArAsVn5nG/C
        qBxZrW042l3AHqB8gzvM46OnB+w55Sh+HguVZeiGVYn4N+FzfI5cRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T15:34:59Z"
  mac: ENC[AES256_GCM,data:XutFUuAZfJlv77H4j5dxwOoGOBqmiBN/HFUd9dSuLt1bSBzphOQJc+0ECmXbKqYXqty46sPMVRpFMdkRHQv1pRyhF1KVWVHyrKhIGiFnFYkPaDvV0vlC45m4wcjQNaiSG5X3a++6bX5gUHl5zxJYjSFKldwlarBB0rMgkz1sW2U=,iv:xBgRrKKgXEJ6lxAOzIt+oaEt8OcxZrDmwS7bUuCHtkg=,tag:RQ45dfQuycaxwUeOMwjh3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
