---
# yaml-language-server: $schema=https://github.com/redpanda-data/redpanda-operator/raw/bd4604e3c6019caeaf9485930adb5e7e8d50c9be/charts/redpanda/chart/values.schema.json
statefulset:
  replicas: 1
  podAntiAffinity:
    type: soft

logging:
  logLevel: warn

storage:
  persistentVolume:
    size: 5Gi

resources:
  cpu:
    cores: 1
  memory:
    container:
      max: 1536Mi
      min: 1Gi
    redpanda:
      memory: 1Gi
      reserveMemory: 0

tls:
  enabled: false

console:
  enabled: true

# post_install_job:
#   enabled: false # not needed for dev

# tuning:
#   tune_aio_events: false        # avoid privileged container

config:
  cluster:
    auto_create_topics_enabled: true
    partition_autobalancing_mode: "off"
    core_balancing_continuous: false
    group_max_session_timeout_ms: 3600000
    # idk it says this is a preset of --mode dev-container
    write_caching_default: true
    group_topic_partitions: 3
    storage_min_free_bytes: 10485760
    topic_partitions_per_shard: 1000
    fetch_reads_debounce_timeout: 10
