# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/listenerset_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: kube-prometheus-stack-prometheus-local
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-local
spec:
  parentRef:
    namespace: istio-system
    name: local
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
    - name: http
      hostname: "prometheus.${LOCAL_DOMAIN}"
      protocol: HTTP
      port: 80
    - name: https
      hostname: "prometheus.${LOCAL_DOMAIN}"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: kube-prometheus-stack-prometheus-local-tls
