---
namespaceOverride: monitoring

alertmanager:
  alertmanagerSpec:
    externalUrl: https://alertmanager.${PUBLIC_DOMAIN}
    volumes:
      - name: &alertmanagerSecret kube-prometheus-stack-alertmanager-telegram
        secret:
          secretName: *alertmanagerSecret
    volumeMounts:
      - name: *alertmanagerSecret
        mountPath: /etc/alertmanager/secrets/telegram

  config:
    route:
      receiver: default
      routes:
        - receiver: default
    receivers:
      - name: default
        telegram_configs:
          - chat_id: -1001644026686
            message_thread_id: 638
            bot_token_file: /etc/alertmanager/secrets/telegram/bot_token

  route:
    http:
      enabled: true
      parentRefs:
        - &publicGateway
          name: public
          sectionName: http-wildcard
          namespace: istio-system
        - &localGateway
          name: local
          sectionName: http-wildcard
          namespace: istio-system
      hostnames: &hostnames
        - alertmanager.${LOCAL_DOMAIN}
        - alertmanager.${PUBLIC_DOMAIN}
      httpsRedirect: true

    https:
      enabled: true
      parentRefs:
        - <<: *publicGateway
          sectionName: https-wildcard
        - <<: *localGateway
          sectionName: https-wildcard
      hostnames: *hostnames

prometheus:
  prometheusSpec:
    externalUrl: https://prometheus.${PUBLIC_DOMAIN}

  route:
    http:
      enabled: true
      parentRefs:
        - <<: *publicGateway
          sectionName: http-wildcard
        - <<: *localGateway
          sectionName: http-wildcard
      hostnames: &hostnames
        - prometheus.${LOCAL_DOMAIN}
        - prometheus.${PUBLIC_DOMAIN}
      httpsRedirect: true

    https:
      enabled: true
      parentRefs:
        - <<: *publicGateway
          sectionName: https-wildcard
        - <<: *localGateway
          sectionName: https-wildcard
      hostnames: *hostnames
