---
flux_install_path: /usr/local/bin
flux_download_url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
flux_github_owner: "{{ github_owner }}"
flux_github_repo: "{{ github_repo }}"
flux_github_token: "{{ github_token }}"
flux_bootstrap_path: "kubernetes/cluster/"
flux_interval: "10m"
flux_components_extra: []
flux_kubeconfig: "/etc/rancher/k3s/k3s.yaml"
flux_age_key_path: "{{ inventory_dir }}/../../secret/age.agekey"
flux_force_rebootstrap: false
