### Gen

# @secret CF_API_TOKEN

POST https://api.cloudflare.com/client/v4/accounts/{{CF_ACCOUNT_ID}}/access/gateway_ca HTTP/1.1
Host: 
Authorization: Bearer {{CF_API_TOKEN}}


### GET

# @secret CF_API_TOKEN

GET https://api.cloudflare.com/client/v4/accounts/{{CF_ACCOUNT_ID}}/access/gateway_ca HTTP/1.1
Host: api.cloudflare.com
Authorization: Bearer {{CF_API_TOKEN}}
