---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-certificate-prod
  namespace: cert-manager
spec:
  issuerRef:
    name: cert-manager-public-prod
    kind: ClusterIssuer
  secretName: public-certificate-prod
  commonName: "kevinnitro.id.vn"
  dnsNames:
    - "kevinnitro.id.vn"
    - "*.kevinnitro.id.vn"
