# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns-config
stringData:
  #ENC[AES256_GCM,data:lXwsvo//DDP/Nt9W5c+y,iv:qBOAvl066i/v9xtEfSsqU/40LMtHHYkxuu/LsAeImH4=,tag:E2Rurpd/RzKssUw1fJvVBA==,type:comment]
  config.json: ENC[AES256_GCM,data:PKBLnNbjk67snGtmWe9wt21ZQ1CvSdqzMY8B6onwl2rwLsmngnGqpHVFkY4D0CwwpCSeJbgsg027IvBjP5KFBNuqLYJCXOPPZwQrHwTvojhxRd9mjbkyBf3f5/PEX9LpX47H8Ccd18oW52m2pJHX5y6NNFSK1UrLYa9nkLQPYgJNECKLsIknBy/pq0wNQ5qoUp41ilqg/RiEJJfgTinAi57ZUcQig6Ag9v1p87Z1MUSzevi4KXJlDGh7nnAhrifuyzdxLgHMJes2tHG5woxVGDJk+A1eMYz06jPdEAC619jKiygGBoUxa7JERKHKZ1lVyKAJ1tdeQ6rPrUsxmPu4sq5R2Y3VK7TY0mfDc5WqX22pKX9GVSIbnQ3/GmtcDTK7XlyMajbpA8WonI6FT9vwYH3/pyjgJjTBb81B3g8wS7+4QHT2oyhvmV8G2MRIqcLbRd26zmxU9ajKESOPOV+3LQ==,iv:48nHXXa/Wkhlbg9ysGcXHtPr1RWh0evYXF+ZYuiXJwI=,tag:BGmvYWZ5ooabRoRBQNlQFw==,type:str]
sops:
  age:
    - recipient: age1ytym5g6mxf0974syp2g2ecrh0y74tnl0u9ee4xm8caawhyv25pls3f2sy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdHlZL3dkV0tjTnlmS1N2
        Ymx3Yk5ldkhmY0tuaHM3TFpvWW16KzZhUGdBCjhVcWdFTFdTazRyeUZVTS9ZUlR4
        ckI5QWUyemdvT2FmaVA5QnN5aTBXUUEKLS0tIFplQTJiWmJ5NHl3RGFITlFhMTZR
        ZERzZFZldng0WlBFS1lDTm4vL1BLWFkKAeGI6VQrGA+qcD7FYaSIH1s6BwMbnoF1
        7V6B3Gzbo9zc+InTOrnfRkjfpy3BpxpUMMdVuLv5mpPcfv9KR74YrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T11:57:25Z"
  mac: ENC[AES256_GCM,data:nAB8vIYYEwtgbCBoZbCAqpOCQ9sjqLYyLZnjQqUkH4Bt/6cLNEdCytgo1AMlvo94Scbt8ZOG5UhRP0Y7EDrmhxF4pU83bMv55aLJUHJ9tL0qVKhgIrdAhuDbF+ZFxbRof6V2eaz/+mEuqW4YNns0eveh5HzkE7rXjimgeSMmuRg=,iv:hfWNTEmzcAFklmc5V18uCN8cz3BnBHTugXtvlwWTf+I=,tag:BDVkze1LC2y2oEXePW0L+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
